# Generated by Django 2.1.2 on 2019-07-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0002_church_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church_Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Church_Vision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='church_background',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='church_background',
            name='vision',
        ),
    ]
